// src/views/Article.tsx
import { format } from 'date-fns';
import React, { memo, useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate, useParams } from 'react-router-dom';
import tw from 'twin.macro';

import IconComments from '~icons/ri/chat-2-line';

import CommentItem from '../components/CommentItem';
import CommentSkeleton from '../components/CommentSkeleton';
import LabelItem from '../components/LabelItem';
import MarkdownHtml from '../components/MarkdownHtml';
import Pagination from '../components/Pagination';
import Skeleton from '../components/Skeleton';
import useHandling from '../hooks/use-handling';
import useQuery from '../hooks/use-query';
import ArticleModel from '../models/ArticleModel';
import CommentModel from '../models/CommentModel';
import github from '../services/github';
import { createQueryURL } from '../utils';

const Wrapper = tw.article`px-8 py-12`;

const Title = tw.h2`text-2xl text-gray-700`;

const Into = tw.div`mt-4 mb-8 space-x-4 flex flex-wrap content-center text-sm text-gray-400`;

const ParagraphSkeleton = tw.ul`mt-8 space-y-4`;

const CommentTitle = tw.h2`text-2xl text-gray-700`;

const CommentButton = tw.a`
  mt-4 block w-full h-10
  leading-10 text-gray-400 text-center
  border border-gray-400 rounded-sm outline-none
  cursor-pointer 
`;

const Foot = tw.div`mt-8 flex justify-center`;

function useArticle() {
  const { id } = useParams();
  const [article, setArticle] = useState<ArticleModel>();

  const [loading, load] = useHandling(
    useCallback(async () => {
      const result = await github.getIssue(parseInt(id!, 10));
      setArticle(ArticleModel.from(result));
    }, [id]),
    true
  );

  useEffect(() => {
    load();
  }, [id]);

  return [loading, article] as const;
}

function useCommentsQuery() {
  const { id } = useParams();
  const { page } = useQuery();

  return useMemo(
    () => ({
      issue: parseInt(id!, 10),
      page: parseInt(page ?? '1', 10),
      pageSize: parseInt(import.meta.env.VITE_COMMENT_PAGE_SIZE, 10),
    }),
    [id, page]
  );
}

function useComments() {
  const query = useCommentsQuery();
  const [comments, setComments] = useState<CommentModel[]>([]);

  const [loading, load] = useHandling(
    useCallback(async () => {
      const result = await github.listComments(query);

      setComments(result.map(CommentModel.from));
    }, [query]),
    true
  );

  useEffect(() => {
    load();
  }, [query]);

  return [loading, comments, query] as const;
}

export default memo(function Article() {
  const navigate = useNavigate();
  const { t } = useTranslation();
  const [articleLoading, article] = useArticle();
  const [commentsLoading, comments, query] = useComments();

  const createdAt = useMemo(() => {
    return article ? format(new Date(article.createdAt), t('dateFormat')) : '';
  }, ['article']);

  const newCommentUrl = useMemo(() => {
    return article ? `${article.htmlUrl}#new_comment_field` : '';
  }, [article]);

  const getLabelLink = useCallback((label: string) => {
    return `../${createQueryURL({ label, page: 1 })}`;
  }, []);

  const onPageChange = useCallback((page: number) => {
    navigate(createQueryURL({ page }));
  }, []);

  return (
    <Wrapper>
      <article>
        {articleLoading && (
          <>
            <Skeleton tw="h-8 w-1/3" />
            <ParagraphSkeleton>
              <Skeleton tw="w-1/2" />
              <Skeleton tw="w-full" />
              <Skeleton tw="w-4/5" />
              <Skeleton tw="w-full" />
              <Skeleton tw="w-3/5" />
              <Skeleton tw="w-full h-40" />
              <Skeleton tw="w-4/5" />
              <Skeleton tw="w-full" />
              <Skeleton tw="w-3/5" />
              <Skeleton tw="w-full" />
              <Skeleton tw="w-2/5" />
            </ParagraphSkeleton>
          </>
        )}

        {article && (
          <>
            <Title>{article.title}</Title>
            <Into>
              <span>{createdAt}</span>
              <span tw="flex items-center">
                {article.labels.map((label) => (
                  <LabelItem
                    key={label.id}
                    label={label}
                    getLink={getLabelLink}
                  />
                ))}
              </span>
              <span tw="flex items-center">
                <IconComments />
                <span tw="ml-1">{article.comments}</span>
              </span>
            </Into>
            <MarkdownHtml markdown={article.body} playground />
          </>
        )}
      </article>

      <section tw="mt-8">
        <CommentTitle>{t('comment.title')}</CommentTitle>
        <CommentButton href={newCommentUrl}>{t('comment.btn')}</CommentButton>

        {commentsLoading && (
          <div>
            {Array.from({ length: 5 }).map((_, i) => (
              <CommentSkeleton key={i} />
            ))}
          </div>
        )}

        {!!comments.length && (
          <div>
            {comments.map((comment) => (
              <CommentItem key={comment.id} comment={comment} />
            ))}
          </div>
        )}

        <Foot>
          <Pagination
            page={query.page}
            pageSize={query.pageSize}
            total={article ? article.comments : 0}
            onChange={onPageChange}
          />
        </Foot>
      </section>
    </Wrapper>
  );
});

// src/views/Article.vue
<template>
  <main w:p="x-8 y-12">
    <article>
      <template v-if="articleLoading || !article">
        <h2 class="skeleton" w:h="!8" w:w="1/3" />
        <ul w:m="t-8" w:space="y-4">
          <li class="skeleton" w:w="1/2" w:m="b-10" />
          <li class="skeleton" w:w="full" />
          <li class="skeleton" w:w="4/5" />
          <li class="skeleton" w:w="full" />
          <li class="skeleton" w:w="3/5" />
          <li class="skeleton" w:w="full" w:h="!50" />
          <li class="skeleton" w:w="4/5" />
          <li class="skeleton" w:w="full" />
          <li class="skeleton" w:w="3/5" />
          <li class="skeleton" w:w="full" />
          <li class="skeleton" w:w="2/5" />
        </ul>
      </template>
      <template v-else-if="article">
        <h2 w:text="2xl gray-700 dark:gray-300">{{ article.title }}</h2>
        <div
          w:m="t-4"
          w:display="flex"
          w:flex="wrap"
          w:align="center"
          w:space="x-4"
          w:text="sm gray-400"
        >
          <span>
            {{ format(new Date(article.createdAt), 'dd / MM / yyyy') }}
          </span>
          <ul w:display="flex" w:align="center">
            <label-item
              v-for="label of article.labels"
              :key="label.id"
              :label="label"
              :get-link="getLabelLink"
            />
          </ul>
          <span>
            <icon-comments w:font="leading-0" w:text="top" />
            <span w:m="l-1">{{ article.comments }}</span>
          </span>
        </div>
        <markdown-html v-if="article" w:m="t-8" :markdown="article.body" playground />
      </template>
    </article>

    <section w:m="t-8">
      <h2 w:text="2xl gray-700 dark:gray-300">{{ t('comment.title') }}</h2>
      <a
        w:m="t-4"
        w:display="block"
        w:w="full"
        w:h="10"
        w:font="leading-10"
        w:border="1 rounded-sm gray-400"
        w:text="gray-400 center"
        w:cursor="pointer"
        w:outline="none focus:none"
        :href="commentUrl"
      >
        {{ t('comment.goto') }}
      </a>
      <ul v-if="commentsLoading">
        <comment-ghost-item v-for="i of 5" :key="i" />
      </ul>
      <ul v-else>
        <comment-item
          v-for="comment of comments"
          :key="comment.id"
          :comment="comment"
          :get-link="getCommentLink"
        />
      </ul>
      <div w:m="t-8" w:display="flex" w:justify="center">
        <pagination :page="page" :page-size="pageSize" :total="total" @change="onPageChange" />
      </div>
    </section>
  </main>
</template>

<script lang="ts" setup>
import { format } from 'date-fns';
import { computed, nextTick, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';

import CommentGhostItem from '~/components/CommentGhostItem.vue';
import CommentItem from '~/components/CommentItem.vue';
import LabelItem from '~/components/LabelItem.vue';
import MarkdownHtml from '~/components/MarkdownHtml.vue';
import Pagination from '~/components/Pagination.vue';
import useHandling from '~/composition/use-handling';
import ArticleModel from '~/models/ArticleModel';
import CommentModel from '~/models/CommentModel';
import github from '~/services/github';
import IconComments from '~icons/ri/chat-2-line';

const route = useRoute();
const router = useRouter();
const { t } = useI18n();

const id = computed(() => parseInt(route.params.id as string, 10) || 0);
const page = computed(() => parseInt(route.query.page as string, 10) || 1);
const pageSize = ref(30);

const article = ref<ArticleModel>();
const comments = ref<CommentModel[]>([]);

const commentUrl = computed(() => {
  return article.value?.htmlUrl + '#new_comment_field';
});

const total = computed(() => article.value?.comments ?? 0);

const [articleLoading, loadArticle] = useHandling(async () => {
  const result = await github.getIssue(id.value);
  article.value = ArticleModel.from(result);
}, true);

const [commentsLoading, loadComments] = useHandling(async () => {
  const result = await github.listComments({
    issue: id.value,
    page: page.value,
    pageSize: pageSize.value,
  });

  comments.value = result.map(CommentModel.from);
}, true);

watch(id, () => loadArticle(), { immediate: true, flush: 'post' });
watch(page, () => loadComments(), { immediate: true, flush: 'post' });

const onPageChange = (page: number) => router.push({ query: { page } });

const getLabelLink = (label: string) => ({ name: 'posts', query: { label, page: 1 } });

const getCommentLink = (id: number) => `${route.path}#comment-${id}`;

watch(commentsLoading, async () => {
  if (comments.value && route.hash) {
    await nextTick();
    const el = document.querySelector(route.hash);
    el?.scrollIntoView();
  }
});
</script>

<i18n lang="json" locale="cn">
{
  "comment": {
    "title": "评论",
    "goto": "点击评论"
  }
}
</i18n>

<i18n lang="json" locale="en">
{
  "comment": {
    "title": "Comments",
    "goto": "Click to Comment"
  }
}
</i18n>
