// src/views/Articles.vue
<template>
  <main w:p="x-8 y-12">
    <h2 v-if="category" w:text="2xl gray-500">
      {{ t(category.title) }}
    </h2>

    <div v-else class="skeleton" w:h="!8" w:w="24" />

    <ul v-if="articlesLoading" w:m="t-8">
      <article-ghost-item v-for="i of 8" :key="i" />
    </ul>

    <ul v-else w:m="t-8">
      <article-item
        v-for="article of articles"
        :key="article.id"
        :article="article"
        :get-link="getArticleLink"
        :get-label-link="getLabelLink"
      />
    </ul>

    <div w:m="t-8" w:display="flex" w:justify="center">
      <pagination :page="page" :page-size="pageSize" :total="total" @change="onPageChange" />
    </div>
  </main>
</template>

<script lang="ts" setup>
import { computed, watch, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useRoute, useRouter } from 'vue-router';

import github from '~/services/github';
import CategoryModel from '~/models/CategoryModel';
import ArticleModel from '~/models/ArticleModel';
import useHandling from '~/composition/use-handling';
import ArticleGhostItem from '~/components/ArticleGhostItem.vue';
import ArticleItem from '~/components/ArticleItem.vue';
import Pagination from '~/components/Pagination.vue';

export type ArticlesProps = {
  milestone: number;
};

const props = defineProps<ArticlesProps>();

const { t } = useI18n();
const route = useRoute();
const router = useRouter();

const label = computed(() => route.query.label as string);
const page = computed(() => parseInt(route.query.page as string, 10) || 1);
const pageSize = ref(10);

const category = ref<CategoryModel>();
const articles = ref<ArticleModel[]>([]);

const total = computed(() => category.value?.articles ?? 0);

const [articlesLoading, loadArticles] = useHandling(async () => {
  if (category.value?.number !== props.milestone) {
    const milestones = await github.listMilestones();
    const milestone = milestones.find((m) => m.number === props.milestone);
    category.value = milestone && CategoryModel.from(milestone);
  }

  const list = await github.listIssues({
    milestone: props.milestone,
    labels: label.value,
    page: page.value,
    pageSize: pageSize.value,
  });

  articles.value = list.map(ArticleModel.from);
}, true);

watch([props, label, page], () => loadArticles(), { immediate: true, flush: 'post' });

const getArticleLink = (id: number) => ({ path: route.path + '/' + id });
const getLabelLink = (label: string) => ({ path: route.path, query: { label, page: 1 } });

const onPageChange = (page: number) => router.push({ query: { page } });
</script>

<i18n lang="json" locale="cn">
{
  "Posts": "文章",
  "Snippets": "代码片段"
}
</i18n>

<i18n lang="json" locale="en">
{
  "Posts": "Posts",
  "Snippets": "Snippets"
}
</i18n>

// src/views/Articles.tsx
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useLocation, useNavigate } from 'react-router-dom';
import tw from 'twin.macro';

import ArticleItem from '../components/ArticleItem';
import ArticleSkeleton from '../components/ArticleSkeleton';
import Pagination from '../components/Pagination';
import Skeleton from '../components/Skeleton';
import useHandling from '../hooks/use-handling';
import useQuery from '../hooks/use-query';
import ArticleModel from '../models/ArticleModel';
import CategoryModel from '../models/CategoryModel';
import github from '../services/github';
import { createQueryURL } from '../utils';

const Wrapper = tw.main`px-8 py-12`;

const Title = tw.h2`text-2xl text-gray-600`;

const List = tw.div`mt-8`;

const Foot = tw.div`mt-8 flex justify-center`;

export type ArticlesProps = {
  milestone: number;
};

function useArticlesQuery() {
  const { labels, page } = useQuery();

  return useMemo(
    () => ({
      labels: labels ?? undefined,
      page: parseInt(page ?? '1', 10),
      pageSize: parseInt(import.meta.env.VITE_ARTICLE_PAGE_SIZE, 10),
    }),
    [labels, page]
  );
}

export default function Articles(props: ArticlesProps) {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const query = useArticlesQuery();

  const [category, setCategory] = useState<CategoryModel>();
  const [articles, setArticles] = useState<ArticleModel[]>([]);
  const total = category?.articles ?? 0;

  const [loadingArticles, loadArticles] = useHandling(
    useCallback(async () => {
      if (category?.number !== props.milestone) {
        const milestones = await github.listMilestones();
        const milestone = milestones.find((m) => m.number === props.milestone);

        if (!milestone) {
          navigate('/404');
          return;
        }

        setCategory(CategoryModel.from(milestone));
      }

      const list = await github.listIssues({
        milestone: props.milestone,
        ...query,
      });

      setArticles(list.map(ArticleModel.from));
    }, [props.milestone, query])
  );

  useEffect(() => {
    loadArticles();
  }, [props.milestone, query]);

  const title = useMemo(() => {
    return category ? t(`tab.${category.title.toLowerCase()}` as any) : '';
  }, [category]);

  const location = useLocation();
  const getArticleLink = useCallback(
    (id: number) => `${location.pathname}/${id}`,
    [location]
  );

  const getLabelLink = useCallback((labels: string) => {
    return createQueryURL({ labels, page: 1 });
  }, []);

  const onPageChange = useCallback(
    (page: number) => {
      navigate(createQueryURL({ page, labels: query.labels }));
    },
    [query.labels, props.milestone]
  );

  return (
    <Wrapper>
      <Skeleton tw="h-8 w-24">
        <Title>{title}</Title>
      </Skeleton>

      <List>
        {loadingArticles
          ? Array.from({ length: 8 }).map((_, i) => <ArticleSkeleton key={i} />)
          : articles.map((article) => (
              <ArticleItem
                key={article.id}
                article={article}
                getLink={getArticleLink}
                getLabelLink={getLabelLink}
              />
            ))}
      </List>

      <Foot>
        <Pagination
          page={query.page}
          pageSize={query.pageSize}
          total={total}
          onChange={onPageChange}
        />
      </Foot>
    </Wrapper>
  );
}
