// src/components/Playground/panes/Console.tsx
import React, { memo } from 'react';
import tw, { styled } from 'twin.macro';
import IconRight from '~icons/ri/arrow-right-s-line';
import IconFatal from '~icons/ri/bug-fill';
import IconError from '~icons/ri/close-circle-fill';
import IconClear from '~icons/ri/delete-bin-line';
import IconWarning from '~icons/ri/error-warning-fill';

const List = tw.ul`m-0 p-0 w-full h-full overflow-auto leading-4 text-sm`;

const Item = styled.li`
  ${tw`p-1 flex items-center text-gray-600 border-b border-gray-100  border-solid`}

  &.info {
    ${tw`text-blue-500`}
  }

  &.warn {
    ${tw`text-yellow-500`}
  }

  &.error {
    ${tw`text-red-500`}
  }
`;

const ClearButton = tw.span`
  absolute bottom-4 right-4
  flex w-9 h-9 items-center justify-center
  hover:text-blue-500 border-gray-50 border rounded-full bg-white shadow-md
  cursor-pointer
`;

export type LogLevel = 'log' | 'info' | 'warn' | 'error' | 'fatal';

export type LogRecord = {
  level: LogLevel;
  message: string[];
  extras?: unknown;
};

const icons = {
  log: IconRight,
  info: IconRight,
  warn: IconWarning,
  error: IconError,
  fatal: IconFatal,
};

const renderIcon = (level: LogLevel) => {
  const Icon = icons[level];
  return <Icon tw="mr-1 opacity-80 text-sm" />;
};

export type ConsoleProps = {
  logs: LogRecord[];
  onClear?: () => void;
};

export default memo(function Console(props: ConsoleProps) {
  const { logs, onClear } = props;

  return (
    <>
      <List>
        {logs.map((log, i) => (
          <Item className={log.level} key={i}>
            {renderIcon(log.level)}
            {log.message.map((msg, j) => (
              <span key={j}>{msg}</span>
            ))}
          </Item>
        ))}
      </List>
      <ClearButton onClick={onClear}>
        <IconClear />
      </ClearButton>
    </>
  );
});

// src/components/Playground/Console.vue
<template>
  <ul class="list">
    <li v-for="(log, i) of logs" :key="i" class="item" :class="log.level">
      <component :is="levelToIcon[log.level]" class="icon" />
      <p class="content">
        <span v-for="(msg, j) of log.message" :key="j">
          {{ msg }}
        </span>
      </p>
    </li>
  </ul>
</template>

<script lang="ts" setup>
import IconRight from '~icons/ri/arrow-right-s-line';
import IconFatal from '~icons/ri/bug-fill';
import IconError from '~icons/ri/close-circle-fill';
import IconWarning from '~icons/ri/error-warning-fill';

import type { LogRecord } from './types';

export type ConsoleProps = {
  logs: LogRecord[];
};

defineProps<ConsoleProps>();

const levelToIcon = {
  log: IconRight,
  info: IconRight,
  warn: IconWarning,
  error: IconError,
  fatal: IconFatal,
};
</script>

<style scoped>
.list {
  @apply m-0 p-0 w-full h-full overflow-auto leading-4 text-sm;
}

.item {
  @apply p-1 flex items-center text-gray-600 dark:text-gray-400 border-b-1 border-light-500 dark:border-dark-300 border-solid;
}

.item .icon {
  @apply mr-1 opacity-80 text-sm;
}

.item .content {
  @apply m-0;
}

.item.info {
  @apply text-blue-500;
}

.item.warn {
  @apply text-orange-500;
}

.item.error {
  @apply text-red-500;
}
</style>
