// src/components/Playground/Playground.vue
<template>
  <div
    w:display="flex"
    w:flex="col"
    w:h="200 lg:120"
    w:border="rounded"
    w:bg="white dark:dark-600"
    w:shadow="md dark-50"
    w:overflow="hidden"
  >
    <header
      w:p="x-4"
      w:display="flex"
      w:align="items-center"
      w:h="10"
      w:border="b-1 solid light-500 dark:dark-300"
      w:text="gray-600 dark:gray-400 sm"
    >
      <icon-code />
      <div w:m="l-2" w:flex="1" w:w="min-0">{{ title }}</div>
      <span w:m="l-auto" w:cursor="pointer" w:font="leading-0" title="copy" @click="onCopy">
        <fade-transition>
          <icon-check v-if="copied" w:text="green-500" />
          <icon-copy v-else w:text="hover:blue-500" />
        </fade-transition>
      </span>
    </header>
    <div w:display="flex" w:flex="1 col lg:row" w:h="min-0">
      <section w:flex="1" w:h="min-0">
        <tabs active-id="source">
          <tab-pane id="source" title="Source">
            <editor :value="code" :language="language" @change="onChange" />
          </tab-pane>
        </tabs>
      </section>
      <section
        w:flex="1"
        w:h="min-0"
        w:border="l-0 lg:l-1 t-1 lg:t-0 light-500 dark:dark-300 solid"
      >
        <tabs v-model:active-id="activeTab">
          <tab-pane id="preview" title="Preview">
            <preview :code="code" :env="env" @log="onLog" />
          </tab-pane>
          <tab-pane id="console" title="Console">
            <Console :logs="logs" />
          </tab-pane>
        </tabs>
      </section>
    </div>
  </div>
</template>

<script lang="ts" setup>
import copy from 'copy-to-clipboard';
import { ref } from 'vue';

import FadeTransition from '~/components/FadeTransition.vue';
import useControlledRef from '~/composition/use-controlled-ref';
import IconCheck from '~icons/ri/checkbox-circle-fill';
import IconCode from '~icons/ri/code-s-slash-line';
import IconCopy from '~icons/ri/file-copy-2-line';

import Console from './Console.vue';
import Editor from './Editor.vue';
import Preview from './Preview.vue';
import TabPane from './TabPane.vue';
import Tabs from './Tabs.vue';
import type { LogRecord } from './types';

export type PlaygroundProps = {
  title?: string;
  language?: string;
  env?: string;
  value?: string;
  defaultValue?: string;
};

export type PlaygroundEmits = {
  (event: 'change', value: string): void;
};

const props = withDefaults(defineProps<PlaygroundProps>(), {
  title: 'Playground',
  language: 'html',
  env: 'html',
  value: undefined,
  defaultValue: '',
});

const emit = defineEmits<PlaygroundEmits>();

const activeTab = ref('preview');

const code = useControlledRef(() => props.value, props.defaultValue);

const onChange = (value: string) => {
  code.value = value;
  emit('change', value);
};

const copied = ref(false);
let copyTimer: ReturnType<typeof setTimeout> | undefined;

const onCopy = () => {
  copied.value = copy(code.value);
  if (copyTimer) clearTimeout(copyTimer);

  copyTimer = setTimeout(() => {
    copied.value = false;
    copyTimer = undefined;
  }, 2000);
};

const logs = ref<LogRecord[]>([]);

const onLog = (log: LogRecord) => {
  logs.value.push(log);
};
</script>

// src/components/Playground/Playground.tsx
import React, { memo, useCallback, useState } from 'react';
import tw, { styled } from 'twin.macro';
import IconCode from '~icons/ri/code-s-slash-line';

import Console, { LogRecord } from './panes/Console';
import Editor from './panes/Editor';
import Preview from './panes/Preview';
import playgrounds, { PlaygroundType } from './playgrounds';

const Wrapper = tw.div`flex flex-col h-[800px] lg:h-[480px] rounded border border-gray-200 bg-white shadow-md overflow-hidden`;

const Toolbar = tw.div`px-4 flex items-center h-10 border-b border-gray-200 text-gray-600`;

const Title = tw.span`ml-2 flex-1 min-w-0`;

const TabButtonGroup = tw.div`ml-auto flex items-center justify-center`;

const TabButton = styled.a<{ active?: boolean }>`
  ${tw`ml-1 px-2 flex items-center justify-center h-7 leading-7 text-sm rounded-sm hover:bg-blue-50 cursor-pointer select-none transition-all duration-200`}
  ${({ active }) => active && tw`bg-blue-100! text-blue-600!`}
`;

const Container = tw.div`flex flex-1 flex-col lg:flex-row min-h-0`;

const TabPane = styled.div<{ visible?: boolean }>`
  :not(:first-of-type) {
    ${tw`border-t lg:border-t-0 lg:border-l border-gray-200`}
  }

  ${tw`relative hidden flex-1 h-full min-h-0 w-full min-w-0`}
  ${({ visible }) => visible && tw`block`}
`;

const allTabs = [
  { key: 'editor', title: 'Editor', visible: false },
  { key: 'preview', title: 'Preview', visible: false },
  { key: 'console', title: 'Console', visible: false },
];

export type PlaygroundProps = {
  type?: PlaygroundType;
  title?: string;
  lang?: string;
  code?: string;
};

export default memo(function Playground(props: PlaygroundProps) {
  const { type = 'js', title = type, lang = 'html', code = '' } = props;
  const [value, setValue] = useState(code);

  const { defaultTabs, sandbox } = playgrounds[type];
  const [activeTabs, setActiveTabs] = useState(() => [...defaultTabs]);

  const onTabToggle = useCallback((e: React.MouseEvent<HTMLAnchorElement>) => {
    const { key } = (e.target as HTMLAnchorElement).dataset;
    if (!key) return;

    setActiveTabs((currentTabs) => {
      if (key === currentTabs[0] && currentTabs.length === 1) {
        return currentTabs;
      }

      return currentTabs.includes(key)
        ? currentTabs.filter((t) => t !== key)
        : [...currentTabs, key];
    });
  }, []);

  const [logs, setLogs] = useState<LogRecord[]>([]);

  const onLog = useCallback((log: LogRecord) => {
    setLogs((oldLogs) => {
      return [...oldLogs, log];
    });
  }, []);

  const onLogClear = useCallback(() => {
    setLogs([]);
  }, []);

  const onValueChange = useCallback((newValue: string) => {
    setValue(newValue);
    onLogClear();
  }, []);

  return (
    <Wrapper>
      <Toolbar>
        <IconCode />
        <Title>{title}</Title>
        <TabButtonGroup>
          {allTabs.map((tab) => (
            <TabButton
              key={tab.key}
              data-key={tab.key}
              active={activeTabs.includes(tab.key)}
              onClick={onTabToggle}
            >
              {tab.title}
            </TabButton>
          ))}
        </TabButtonGroup>
      </Toolbar>
      <Container>
        <TabPane visible={activeTabs.includes('editor')}>
          <Editor value={value} lang={lang} onChange={onValueChange} />
        </TabPane>
        <TabPane visible={activeTabs.includes('preview')}>
          <Preview code={value} sandbox={sandbox} onLog={onLog} />
        </TabPane>
        <TabPane visible={activeTabs.includes('console')}>
          <Console logs={logs} onClear={onLogClear} />
        </TabPane>
      </Container>
    </Wrapper>
  );
});
