// src/components/Playground/Preview.vue
<template>
  <div ref="container" w:w="full" w:h="full" w:p="4"></div>
</template>

<script lang="ts" setup>
import { onMounted, onUnmounted, ref, watch } from 'vue';

import { ensureArray } from '~/utils';

import type { SandboxInstance } from './sandbox/Sandbox';
import DefaultSandbox from './sandbox/Sandbox';
import VueSfcSandbox from './sandbox/VueSfcSandbox';
import type { LogRecord } from './types';

const sandboxes: Record<string, SandboxInstance> = {
  html: DefaultSandbox,
  'vue-sfc': VueSfcSandbox,
};

export type PreviewProps = {
  code: string;
  env: string;
};

export type PreviewEmits = {
  (event: 'log', log: LogRecord): void;
};

const props = defineProps<PreviewProps>();
const emit = defineEmits<PreviewEmits>();

const Sandbox: SandboxInstance = sandboxes[props.env] || sandboxes.html;

const container = ref<HTMLDivElement>();
const sandbox = new Sandbox();

const onMessage = (e: MessageEvent) => {
  const args = e.data.args;
  emit('log', { level: args.level, message: ensureArray(args.message) });
};

onMounted(() => {
  if (container.value) {
    sandbox.mount(container.value, props.code);
    window.addEventListener('message', onMessage);
  }
});

onUnmounted(() => {
  window.removeEventListener('message', onMessage);
});

watch(
  () => props.code,
  () => sandbox.update(props.code),
);
</script>

// src/components/Playground/panes/Preview.tsx
import React, { memo, useCallback, useEffect, useRef } from 'react';
import tw from 'twin.macro';

import { ensureArray } from '../../../utils';
import JsSandbox, { SandboxInstance } from '../sandboxes/Sandbox';
import { LogRecord } from './Console';

const Wrapper = tw.div`p-4 w-full h-full`;

export type PreviewProps = {
  code: string;
  sandbox: SandboxInstance;
  onLog?: (log: LogRecord) => void;
};

export default memo(function Preview(props: PreviewProps) {
  const { code, sandbox: Sandbox, onLog } = props;

  const container = useRef<HTMLDivElement | null>(null);
  const sandbox = useRef<JsSandbox>();

  const onMessage = useCallback(
    (e: MessageEvent) => {
      const { args } = e.data;
      onLog?.({ level: args.level, message: ensureArray(args.message) });
    },
    [onLog],
  );

  useEffect(() => {
    if (container.current) {
      sandbox.current = new Sandbox();
      sandbox.current.mount(container.current, code);
      window.addEventListener('message', onMessage);
    }

    return () => {
      window.removeEventListener('message', onMessage);
    };
  }, []);

  useEffect(() => {
    sandbox.current?.update(code);
  }, [code]);

  return <Wrapper ref={container} />;
});
