// src/components/LabelItem.vue
<template>
  <li w:m="r-4">
    <router-link :to="getLink(label.name)" w:display="flex" w:align="items-center">
      <span :style="{ background: label.color }" w:w="2" w:h="2" w:border="rounded-full" />
      <span w:m="l-2">{{ label.name }}</span>
    </router-link>
  </li>
</template>

<script lang="ts" setup>
import LabelModel from '~/models/LabelModel';

export type LabelItemProps = {
  label: LabelModel;
  getLink: (label: string) => unknown;
};

defineProps<LabelItemProps>();
</script>

// src/components/LabelItem.tsx
import React from 'react';
import { Link, To } from 'react-router-dom';
import tw from 'twin.macro';

import LabelModel from '../models/LabelModel';

const Wrapper = tw(Link)`mr-4 flex items-center`;

const Dot = tw.span`w-2 h-2 rounded-full`;

const Title = tw.span`ml-2`;

export type LabelItemProps = {
  label: LabelModel;
  getLink: (label: string) => To;
};

export default function LabelItem(props: LabelItemProps) {
  const { label, getLink } = props;

  return (
    <Wrapper to={getLink(label.name)}>
      <Dot style={{ background: label.color }} />
      <Title>{label.name}</Title>
    </Wrapper>
  );
}
