// src/components/MarkdownHtml.vue
<template>
  <div ref="container" class="markdown-body" v-html="html" />
</template>

<script lang="ts" setup>
import 'github-markdown-css/github-markdown.css';

import { ref, nextTick, watch, onMounted, createApp, App } from 'vue';
import Prism from 'prismjs';
import MarkdownIt from 'markdown-it';
import Playground from '~/components/Playground/Playground.vue';

export type MarkdownHtmlProps = {
  playground?: boolean;
  markdown: string;
};

const props = defineProps<MarkdownHtmlProps>();

const parseArgs = (raw: string): Record<string, string> => {
  const re = /(\w+)="([^"]*)"/g;
  const args: Record<string, string> = {};

  for (const matched of raw.matchAll(re)) {
    args[matched[1]] = matched[2];
  }

  const [lang] = raw.split(' ', 1);
  if (lang) args['lang'] = lang;

  return args;
};

const highlight = (text: string, lang: string) => {
  const grammar = Prism.languages[lang] ?? Prism.languages.plain;
  return Prism.highlight(text, grammar, lang);
};

const container = ref<HTMLDivElement>();
const html = ref('');
const playgrounds = ref<App[]>([]);

const toHtml = (markdown: string) => {
  if (!markdown) return '';

  const md = new MarkdownIt({ highlight });
  const defaultFence = md.renderer.rules.fence;

  md.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const { content, info } = tokens[idx];
    const args = parseArgs(info);

    if (props.playground && args.playground) {
      const el = document.createElement('div');

      Object.assign(el.dataset, {
        playground: 'true',
        title: args.playground,
        env: args.playground,
        language: args.lang,
        defaultValue: content,
      });

      return el.outerHTML;
    }

    return defaultFence?.(tokens, idx, options, env, self) || '';
  };

  return md.render(props.markdown);
};

onMounted(() => {
  watch(
    () => props.markdown,
    async () => {
      if (!container.value) return;

      if (playgrounds.value.length) {
        playgrounds.value.forEach((app) => app.unmount());
        playgrounds.value = [];
      }

      html.value = toHtml(props.markdown);
      await nextTick();

      container.value.querySelectorAll('[data-playground]').forEach((el) => {
        const props = (el as HTMLDivElement).dataset;
        const app = createApp(Playground, props);

        app.mount(el);
        playgrounds.value.push(app);
      });
    },
    { immediate: true },
  );
});
</script>

<style>
.markdown-body {
  @apply dark:text-gray-300;
}

.markdown-body pre {
  @apply bg-white dark:bg-dark-600 shadow-md shadow-dark-50;
}
</style>

// src/components/MarkdownHtml.tsx
import MarkdownIt from 'markdown-it';
import React, { memo, useEffect, useRef, useState } from 'react';
import { Root, createRoot } from 'react-dom/client';
import tw, { styled } from 'twin.macro';

import { highlight } from '../utils';
import Playground from './Playground';

const Container = styled.div`
  ${tw`bg-transparent!`}

  > pre {
    ${tw`rounded shadow-md border border-gray-200 bg-white dark:bg-slate-800 dark:border-gray-800`}
  }
`;

const parseArgs = (raw: string): Record<string, string> => {
  const re = /(?<key>\w+)="(?<value>[^"]*)"/g;
  const args: Record<string, string> = {};

  for (const matched of raw.matchAll(re)) {
    const { key, value } = matched.groups!;
    args[key] = value;
  }

  const [lang] = raw.split(' ', 1);
  if (lang) args.lang = lang;

  return args;
};

const toHtml = (markdown: string, playground?: boolean) => {
  if (!markdown) return '';

  const md = new MarkdownIt({ highlight });
  const defaultFence = md.renderer.rules.fence;

  md.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const { content, info } = tokens[idx];
    const args = parseArgs(info);

    if (playground && args.playground) {
      const el = document.createElement('div');

      Object.assign(el.dataset, {
        playground: 'true',
        type: args.playground,
        title: args.playground,
        lang: args.lang,
        code: content,
      });

      return el.outerHTML;
    }

    return defaultFence?.(tokens, idx, options, env, self) || '';
  };

  return md.render(markdown);
};

export type MarkdownHtmlProps = {
  markdown: string;
  playground?: boolean;
};

export default memo(function MarkdownHtml(props: MarkdownHtmlProps) {
  const { markdown, playground } = props;

  const container = useRef<HTMLDivElement>(null);
  const playgrounds = useRef<Root[]>([]);
  const [html, setHtml] = useState('');

  useEffect(() => {
    setHtml(toHtml(markdown, playground));
  }, []);

  useEffect(() => {
    if (!container.current) return;

    container.current.querySelectorAll<HTMLDivElement>('[data-playground]').forEach((el) => {
      const root = createRoot(el);
      root.render(<Playground {...el.dataset} />);
      playgrounds.current.push(root);
    });
  }, [html]);

  useEffect(() => {
    return () => {
      playgrounds.current.forEach((root) => {
        root.unmount();
      });
    };
  }, []);

  return (
    <Container
      ref={container}
      className="markdown-body"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
});
